### PR TITLE
build: multi-arch-test-build: support apk in artifacts

### PR DESCRIPTION
**Pull request by Habbie**

### CODE REVIEW

**Comment by Ansuel** [comment]
Mhh do we need the index.json ?

Thanks for taking care!

**Comment by Ansuel** [comment]
I mean why it was added in the first place? ahaahahah

**Comment by Habbie** [comment]
> I mean why it was added in the first place? ahaahahah

I'm not even sure where it comes from

**Comment by Habbie** [comment]
but, if you're asking why I added it, I added it because I saw it in the `cp -v` output :)

**Comment by Ansuel** [comment]
@Habbie if you are ok with this and you don't get annoyed I would ask you
1. Drop the index.json
2. split this in 2 commits one for the -v change and one for the apk...

Also would prefer to have a more explicit pattern for ipk or apk (instead of using [ia])

Also any chance you can add a commit description (even repetition of title with different words) and signed off by tag?

**Comment by Habbie** [comment]
> Also would prefer to have a more explicit pattern for ipk or apk (instead of using [ia])

if you mean `*.ipk *.apk`, the problem with that is that one of them will generate an error. that's why I did `[ia]`

**Comment by Habbie** [comment]
> if you are ok with this and you don't get annoyed I would ask you

done, signed off, added a few words to the second commit message

**Pull request merged**
